### ISSUE TITLE
Remove intellij configuration from the repository

### ISSUE THREAD

**Issue by DavideD** [hibernate/hibernate-rx#59]
I don't like to have it there.
As far as I know we don't do it with other projects and I find annoying to have it change every time somebody push something or I decide to tweak a bit my IDE.

**Comment by gavinking** [comment]
Alright so I tried this out and indeed on this project the import seemed to work smoothly (first time that's worked for me) without the `.idea` directory. Perhaps because this project was initially created as a simple, clean gradle build.

The only thing I dislike is that of course it uses the global settings for code style, which is a pain because Hibernate uses tabs whereas the other projects I work on all uses spaces. Still, that's not *so* bad compared to my experiences with the `hibernate-orm` and `query-validator` projects.

**Comment by DavideD** [comment]
> The only thing I dislike is that of course it uses the global settings for code style, which is a pain because Hibernate uses tabs whereas the other projects I work on all use spaces

You only need to set the code style only once, or am I missing something? Checkstyle also make sure that there are no errors and while this is annoying in the beginning I think people tend to get use to it quickly.

I'm going to add a CONTRIBUTING.md to the project with some specific information.
