### ISSUE TITLE
Convert from Axle to Mutiny

### ISSUE THREAD

**Issue by aguibert** [hibernate/hibernate-rx#84]
According to @Sanne the strategy going forward should be to use Mutiny instead of Axle, so we should convert dependencies over and also upgrade to the newest version of Mutiny (0.0.14 as of writing this).

**Comment by gavinking** [comment]
Well wait up

**Comment by gavinking** [comment]
Look, the actual thing that is being proposed, _that has not been fully discussed and agreed upon yet_, is to migrate the _API_ of Hibernate RX to use `Uni`/`Multi` instead of `CompletionStage`, or possibly offer both options.

Now, if we're planning on *only* supporting `Uni`/`Multi`, then what we would be doing here is going through all the code of Hibernate RX and migrating all of it away from `CompletionStage`. On the other hand, if we decide it's worth maintaining both APIs as options, then it seems to me that we should be offering the Mutiny API as a separate optional façade, and retaining the use of `CompletionStage` throughout the rest of the code base.

Whatever, this issue is not a simple matter of "swap out axle and add an unnecessary dependency on mutiny when we're not even using it's APIs". That doesn't make sense at all.

**Comment by DavideD** [comment]
> Now, if we're planning on only supporting Uni/Multi, then what we would be doing here is going through all the code of Hibernate RX and migrating all of it away from CompletionStage.

That's what I was expecting and I think it would be nice to see what it involves with an initial PR.

> On the other hand, if we decide it's worth maintaining both APIs as options, then it seems to me that we should be offering the Mutiny API as a separate optional façade, and retaining the use of CompletionStage throughout the rest of the code base.

As far as I can see converting a Uni/Multi to CompletionStage is quite trivial, so mantaining both API could be done by adding a facade on top of Mutiny that converts the results to CompletionStage (I think).

Wouldn't that make sense?

**Comment by aguibert** [comment]
+1 on using Uni/Multi by default. I think it's very similar to Reactor's Mono/Flux concept which I like a lot and it is easy for users to grasp. 

Since it's so easy to convert to completion stage (just tack on `.convert().toCompletionStage()`) we may not even need to provide a facade since users could easily convert on their own. We could always provide a facade later if we find that users prefer CompletionStage.

**Comment by gavinking** [comment]
Right, but here's my issue: Mutiny and `CompletionStage` aren't AFAIK the only things in the whole wide reactive universe, and at some stage we might want to support something else as well. If that's likely, then it seems to me that it would make more sense to retain `CompletionStage` as the "lowest common denominator" thing, merely because it's right there in the JDK, and doesn't require that people who're using something other than Mutiny still drag along Mutiny as a dependency.

Note: it's not that I'm attached to `CompletionStage` _at all_ (just like @FroMage, I think it's a mess of an API, actually), nor that I'm at all hostile to Mutiny (I have not even looked at it yet, but I trust you guys that it's much better).

**Comment by gavinking** [comment]
(If `MutinySession` is just a façade, then I suppose that mutiny could be an optional dependency. But if we reimplement this project to use mutiny APIs internally, then it's going to be a hard requirement at runtime.)

**Comment by aguibert** [comment]
That's a very valid point @gavinking. I think the thing that would make Mutiny a good base-requirement option is the fact that it has explicit bridge methods for all of the big reactive APIs out there today: CompletionStage, Reactor, and RxJava (see the "[How do I interact with X](https://smallrye.io/smallrye-mutiny/#_how_do_i_interact_with_completionstages)" sections)

To me this makes Mutiny look like a really attractive API to use internally, because we won't be on the hook for maintaining the conversion logic to CS/Reactor/RxJava. If Mutiny was "yet another reactive API" I would quickly dismiss it as an option, but the interop features it has with the other APIs makes it really compelling IMO.

**Comment by Sanne** [comment]
I would prefer having Mutiny only on the exposed API initially: it's a very
young project and we don't know yet how cast in stone it is, how it
performs, etc..

Of course I don't mean it should be strictly exclusively referenced in the
API but take the boundaries in the most pragmatic manner, and keeping in
mind that indeed we'd prefer to keep our options open to other models.

We could eventually have multiple public APIs so to have something for each
flavour of reactive - hopefully basing this on the Mutiny adaptors but
keeping in mind we might have to adapt.

**Comment by aguibert** [comment]
Closing this issue as a duplicate of #94
